apiVersion: v1
data:
  application.conf: |
    server {
      host: "0.0.0.0"
      host: ${?HOST}
      port: 7070
      port: ${?PORT}
    }

    client {
      connect-timeout: 2m
      proxy-host: "140.227.211.47"
      proxy-port: 8080
    }

    mongo {
      connection-uri: "mongodb+srv://"${?MONGO_USER}":"${?MONGO_PASSWORD}"@"${?MONGO_HOST}"/ebay-app"
      db-name: "ebay-app"
    }
    
    telegram {
      base-uri: "https://api.telegram.org"
      bot-key: ${?TELEGRAM_BOT_API_KEY}
      main-channel-id: ${?TELEGRAM_CHANNEL_ID}
      secondary-channel-id: ${?TELEGRAM_SECONDARY_CHANNEL_ID}
      alerts-channel-id: ${?TELEGRAM_ALERTS_CHANNEL_ID}
      headers: {}
    }
    
    retailer {
      cex {
        base-uri: "https://fs2-proxy.herokuapp.com"
        cache {
          expiration: 24h
          validation-period: 1h
        }
        headers {
          "X-Reroute-To": "https://wss2.cex.uk.webuy.io"
          "X-Reload-On-403": "true"
        }
      }
  
      ebay {
        base-uri: "https://api.ebay.com"
        credentials: [
          {client-id: ${?EBAY_CLIENT_ID}, client-secret: ${?EBAY_CLIENT_SECRET}}
          {client-id: ${?EBAY_CLIENT_ID_2}, client-secret: ${?EBAY_CLIENT_SECRET_2}}
          {client-id: ${?EBAY_CLIENT_ID_2}, client-secret: ${?EBAY_CLIENT_SECRET_3}}
          {client-id: ${?EBAY_CLIENT_ID_4}, client-secret: ${?EBAY_CLIENT_SECRET_4}}
        ]
        search {
          min-feedback-score: 5
          min-feedback-percentage: 92
          max-listing-duration: 20m
        }
        headers: {}
      }
  
      selfridges {
        base-uri: "https://fs2-proxy.herokuapp.com"
        delay-between-individual-requests: 2s
        headers: {
          "user-agent": "PostmanRuntime/7.28.3"
          "referer": "https://www.selfridges.com"
          "api-key": ${?SELFRIDGES_API_KEY}
          "X-Reload-On-403": "true"
          "X-Reroute-To": "https://www.selfridges.com"
        }
      }
  
      argos {
        base-uri: "https://www.argos.co.uk"
        proxied: true
        headers: {}
      }
  
      jdsports {
        base-uri: "https://fs2-proxy.herokuapp.com"
        headers {
          "X-Reroute-To": "https://www.jdsports.co.uk"
          "X-Reload-On-403": "true"
        }
        delay-between-individual-requests: 2s
      }
  
      scotts {
        base-uri: "https://fs2-proxy.herokuapp.com"
        headers {
          "X-Reroute-To": "https://www.scottsmenswear.com"
          "X-Reload-On-403": "true"
        }
        delay-between-individual-requests: 2s
      }
  
      tessuti {
        base-uri: "https://fs2-proxy.herokuapp.com"
        headers {
          "X-Reroute-To": "https://www.tessuti.co.uk"
          "X-Reload-On-403": "true"
        }
        delay-between-individual-requests: 2s
      }
  
      nvidia {
        base-uri: "https://api.nvidia.partners"
        proxied: true
        headers: {}
      }
  
      scan {
        base-uri: "https://www.scan.co.uk"
        proxied: true
        headers {
          "X-Forwarded-For": "92.7.76.29"
        }
      }
  
      harvey-nichols {
        base-uri: "https://proxy-kirill5k.cloud.okteto.net"
        delay-between-individual-requests: 15s
        headers {
          "X-Reroute-To": "https://www.harveynichols.com"
          "X-Reload-On-403": "true"
          "Accept": "application/json, text/javascript, */*; q=0.01"
          "Cache-Control": "no-cache"
          "Connection": "keep-alive"
          "x-requested-with": "XMLHttpRequest"
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 OPR/82.0.4227.33"
          "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8"
          "Accept-Encoding": "gzip, deflate, br"
        }
      }
  
      mainline-menswear {
        base-uri: "https://fs2-proxy.herokuapp.com"
        headers {
          "X-Reroute-To": "https://livewebapi.mainlinemenswear.co.uk"
        }
      }
    }

    stock-monitor {
      cex {
        monitoring-frequency: 10m
        monitoring-requests: [
          //{search-criteria: {query: "airpods max space grey"}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      nvidia {
        monitoring-frequency: 1m
        monitoring-requests: [
          {search-criteria: {query: "geforce", category: "GPU", exclude-filters: ["GTX 1650", "GTX 1660"]}, monitor-stock-change: true, monitor-price-change: true}
        ]
      }

      argos {
        monitoring-frequency: 10m
        monitoring-requests: [
          //{search-criteria: {query: "PlayStation 5 Console"}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      tessuti {
        delay-between-requests: 30s
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {category: "men", query: "Emporio Armani", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Emporio Armani EA7", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Hugo", min-discount: 53}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Boss", min-discount: 53}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "calvin-klein-jeans", min-discount: 53}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Tommy Hilfiger", min-discount: 53}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Moschino", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Stone Island", min-discount: 39}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Kenzo", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Moncler", min-discount: 29}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      scotts {
        delay-between-requests: 30s
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {query: "Emporio Armani EA7", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "EA7", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "Boss", min-discount: 53}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "Hugo", min-discount: 53}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "emporio-armani-loungewear", min-discount: 53}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      jdsports {
        delay-between-requests: 30s
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {category: "men", query: "Emporio Armani EA7", min-discount: 45}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Calvin Klein", min-discount: 59}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Boss", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "boss-loungewear", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Hugo", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "tommy-hilfiger", min-discount: 59}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      selfridges {
        delay-between-requests: 30s
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {query: "stone-island", min-discount: 39}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "emporio armani", min-discount: 44}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "kenzo", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "moncler", min-discount: 10}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "tommy hilfiger", min-discount: 59}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "polo ralph lauren", min-discount: 59}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "hugo", min-discount: 48}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "boss", min-discount: 48}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      harvey-nichols {
        delay-between-requests: 2m
        monitoring-frequency: 12m
        monitoring-requests: [
          //{search-criteria: {query: "gucci", min-discount: 24}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "off-white", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "boss", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "kenzo", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "emporio armani", min-discount: 49}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }
    
      mainline-menswear {
        delay-between-requests: 30s
        monitoring-frequency: 12m
        monitoring-requests: [
          {search-criteria: {query: "moschino", min-discount: 54}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "ea7 emporio armani", min-discount: 54}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "boss bodywear", min-discount: 54}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "boss athleisure", min-discount: 54}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "boss casual", min-discount: 54}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "emporio armani", min-discount: 54}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      scan {
        monitoring-frequency: 15m
        monitoring-requests: [
          //{search-criteria: {category: "gpu-nvidia-gaming", query: "all"}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }
    
      ebay {
        monitoring-frequency: 10m
        monitoring-requests: [
          //{search-criteria: {item-kind: "generic", query: "nanoleaf shapes", category: "smart-lighting"}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }
    }

    deals-finder {
      ebay {
        search-frequency: 60s
        search-requests: [
          {search-criteria: {query: "PS4", item-kind: "video-game", category: "games-ps4-ps5"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "XBOX ONE", item-kind: "video-game", category: "games-xbox-one-series-x"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "PS5", item-kind: "video-game", category: "games-ps4-ps5"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "XBOX SERIES", item-kind: "video-game", category: "games-xbox-one-series-x"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "SWITCH", item-kind: "video-game", category: "games-switch"}, min-margin: 45, max-quantity: 10}
        ]
        delay-between-requests: 5s
      }
    }
kind: ConfigMap
metadata:
  name: fs2-app-core-config
