apiVersion: v1
data:
  application.conf: |
    server {
      host: "0.0.0.0"
      host: ${?HOST}
      port: 7070
      port: ${?PORT}
    }

    client {
      connect-timeout: 2m
      proxy-host: "140.227.211.47"
      proxy-port: 8080
    }

    mongo {
      connection-uri: "mongodb+srv://"${?MONGO_USER}":"${?MONGO_PASSWORD}"@"${?MONGO_HOST}"/ebay-app"
      db-name: "ebay-app"
    }
    
    telegram {
      base-uri: "https://api.telegram.org"
      bot-key: ${?TELEGRAM_BOT_API_KEY}
      main-channel-id: ${?TELEGRAM_CHANNEL_ID}
      secondary-channel-id: ${?TELEGRAM_SECONDARY_CHANNEL_ID}
      alerts-channel-id: ${?TELEGRAM_ALERTS_CHANNEL_ID}
      headers: {}
    }
    
    retailer {
      cex {
        //base-uri: "https://p01--api--smb9w7tyzdrk.code.run"
        base-uri: "https://reqfol.fly.dev"
        cache {
          expiration: 24h
          validation-period: 1h
        }
        headers {
          "X-Reroute-To": "https://lnnfeewzva-dsn.algolia.net"
        }
        query-parameters {
          "x-algolia-agent": "Algolia for JavaScript (4.13.1); Browser (lite); instantsearch.js (4.41.1); Vue (2.6.14); Vue InstantSearch (4.3.3); JS Helper (3.8.2)"
          "x-algolia-api-key": ${?CEX_ALGOLIA_API_KEY}
          "x-algolia-application-id": ${?CEX_ALGOLIA_APP_ID}
        }
      }
  
      ebay {
        base-uri: "https://api.ebay.com"
        credentials: [
          {client-id: ${?EBAY_CLIENT_ID}, client-secret: ${?EBAY_CLIENT_SECRET}}
          {client-id: ${?EBAY_CLIENT_ID_2}, client-secret: ${?EBAY_CLIENT_SECRET_2}}
          {client-id: ${?EBAY_CLIENT_ID_2}, client-secret: ${?EBAY_CLIENT_SECRET_3}}
          {client-id: ${?EBAY_CLIENT_ID_4}, client-secret: ${?EBAY_CLIENT_SECRET_4}}
        ]
        search {
          min-feedback-score: 5
          min-feedback-percentage: 92
          max-listing-duration: 20m
        }
        headers: {}
      }
  
      selfridges {
        base-uri: "https://reqfol.fly.dev"
        delay-between-individual-requests: 2s
        headers: {
          "api-key": ${?SELFRIDGES_API_KEY}
          "X-Reroute-To": "https://www.selfridges.com"
          "X-Reload-On-403": "true"
        }
      }
  
      argos {
        base-uri: "https://www.argos.co.uk"
        proxied: true
        headers: {}
      }
  
      jdsports {
        base-uri: "https://p01--api--smb9w7tyzdrk.code.run"
        //base-uri: "https://request-follower.fly.dev"
        //base-uri: "https://reqfol.fly.dev"
        base-uri: "https://www.jdsports.co.uk"
        headers {
          "X-Reroute-To": "https://www.jdsports.co.uk"
          "X-Reload-On-403": "true"
        }
        delay-between-individual-requests: 2s
      }
  
      nvidia {
        //base-uri: "https://p01--api--smb9w7tyzdrk.code.run"
        base-uri: "https://reqfol.fly.dev"
        headers: {
          "X-Reroute-To": "https://api.nvidia.partners"
        }
      }
  
      scan {
        base-uri: "https://www.scan.co.uk"
        proxied: true
        headers {
          "X-Forwarded-For": "92.7.76.29"
        }
      }
  
      harvey-nichols {
        base-uri: "https://reqfol.fly.dev"
        delay-between-individual-requests: 15s
        headers {
          "X-Reroute-To": "https://www.harveynichols.com"
          "X-Reload-On-403": "true"
          "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8"
        }
      }
  
      mainline-menswear {
        //base-uri: "https://request-follower.fly.dev"
        base-uri: "http://mdrhnkozaf.eu08.qoddiapp.com"
        headers {
          "X-Reroute-To": "https://livewebapi.mainlinemenswear.co.uk"
        }
      }
    
      flannels {
        //base-uri: "https://p01--api--smb9w7tyzdrk.code.run"
        base-uri: "https://reqfol.fly.dev"
        headers: {
          "X-Reroute-To": "https://www.flannels.com"
        }
      }
    
      tessuti {
        //base-uri: "https://p01--api--smb9w7tyzdrk.code.run"
        base-uri: "https://reqfol.fly.dev"
        headers {
          "X-Reroute-To": "https://www.tessuti.co.uk"
          "X-Reload-On-403": "true"
        }
        delay-between-individual-requests: 2s
      }
    
      scotts {
        //base-uri: "https://p01--api--smb9w7tyzdrk.code.run"
        base-uri: "https://reqfol.fly.dev"
        headers {
          "X-Reroute-To": "https://www.scottsmenswear.com"
          "X-Reload-On-403": "true"
        }
        delay-between-individual-requests: 2s
      }
    }

    stock-monitor {
      cex {
        delay-between-requests: 30s
        monitoring-frequency: 10m
        monitoring-requests: [
          //{search-criteria: {query: "Apple iPad Pro 11 3rd Gen (A2377) 128GB", filters: {"include": ["WiFi A"]}}, monitor-stock-change: true, monitor-price-change: true}
          //{search-criteria: {query: "Apple iPad Pro 11 3rd Gen (A2377) 128GB", filters: {exclude: ["WiFi A"]}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "Watch Series Ultra (Cel) NO STRAP, Titanium", filters: {"include": ["49mm, A"]}}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      nvidia {
        monitoring-frequency: 10m
        monitoring-requests: [
          {search-criteria: {query: "geforce", category: "GPU"}, monitor-stock-change: true, monitor-price-change: true}
        ]
        filters: {exclude: ["GTX 1650", "GTX 1660"]}
      }

      argos {
        monitoring-frequency: 10m
        monitoring-requests: [
          //{search-criteria: {query: "PlayStation 5 Console"}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }

      jdsports {
        delay-between-requests: 45s
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {category: "men", query: "Emporio Armani EA7"}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Boss"}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "men", query: "Hugo"}, monitor-stock-change: false, monitor-price-change: true}
        ]
        filters: {
          exclude: ["size (\\d+(l|s)|3[1-9]R|(\\d)?xl|xxl|xxxl|l|\\b[1-8]\\b|1\\d|\\d+Y)", "mini crossbody", "\\bcap\\b"], 
          min-discount: 49
        }
      }

      selfridges {
        delay-between-requests: 30s
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {query: "stone-island", filters: {min-discount: 29}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "emporio armani", filters: {min-discount: 44}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "kenzo", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "moncler", filters: {min-discount: 10}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "hugo", filters: {min-discount: 48}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "boss", filters: {min-discount: 48}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "diesel", filters: {min-discount: 48, "include": ["jeans"]}}, monitor-stock-change: false, monitor-price-change: true}
        ]
        filters: {exclude: ["size (3[1-9]R|(\\d)?xl|xxl|xxxl|l|\\b[1-8]\\b|1\\d|\\d+Y)"]}
      }
    
      flannels {
        delay-between-requests: 3m
        monitoring-frequency: 12m
        monitoring-requests: [
          {search-criteria: {query: "stone-island", category: mens}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "off-white", category: mens, filters: {min-discount: 40}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "palm-angels", category: mens, filters: {min-discount: 40}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "kenzo", category: mens, filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
        ]
        filters: {
          exclude: ["size (\\dX(S|L)|\\b[1-8]\\b|\\b1\\d\\b|3[2-9]R)", "\\bmask\\b", "socks|formal pants|olive"], 
          min-discount: 28, 
          max-price: 250
        }
      }
    
      tessuti {
        delay-between-requests: 30s
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {category: "mens", query: "Emporio Armani", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "mens", query: "ea7", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {category: "mens", query: "Moschino", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {category: "mens", query: "Hugo", filters: {min-discount: 53}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {category: "mens", query: "Boss", filters: {min-discount: 53}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {category: "mens", query: "Moncler"}, monitor-stock-change: false, monitor-price-change: true}
        ]
        filters: {
          exclude: ["size (\\d+(l|s)|3[1-9](W|R)|(\\d)?xl|xxl|xxxl|l|\\b[1-8]\\b|1\\d|\\\\d+Y)", "mini crossbody", "shoulder bag", "\\bcap\\b"], 
          min-discount: 29,
          max-price: 80
        }
      }

      scotts {
        delay-between-requests: 1m
        monitoring-frequency: 6m
        monitoring-requests: [
          {search-criteria: {query: "Emporio Armani", category: mens}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "EA7", category: mens}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "Kenzo", category: mens}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "Boss", category: mens, filters: {min-discount: 53}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "Hugo", category: mens, filters: {min-discount: 53}}, monitor-stock-change: false, monitor-price-change: true}
          {search-criteria: {query: "diesel", category: mens, filters: {min-discount: 60, "include": ["jeans"]}}, monitor-stock-change: false, monitor-price-change: true}
        ]
        filters: {
          exclude: ["size (\\d+(l|s)|3[1-9](R|W)|(\\d)?xl|xxl|xxxl|l|\\b[1-8]\\b|1\\d|\\d+Y)", "mini crossbody", "shoulder bag", "\\bcap\\b"], 
          min-discount: 49,
          max-price: 250
        }
      }

      harvey-nichols {
        delay-between-requests: 3m
        monitoring-frequency: 12m
        monitoring-requests: [
          //{search-criteria: {query: "Moncler Maya navy quilted shell jacket"}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "gucci", filters: {min-discount: 24}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "off-white", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "stone island", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "kenzo", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "emporio armani", filters: {min-discount: 49}}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }
    
      mainline-menswear {
        delay-between-requests: 1m
        monitoring-frequency: 12m
        monitoring-requests: [
          //{search-criteria: {query: "moschino"}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "ea7 emporio armani"}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "boss bodywear"}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "boss athleisure"}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "boss casual"}, monitor-stock-change: false, monitor-price-change: true}
          //{search-criteria: {query: "emporio armani"}, monitor-stock-change: false, monitor-price-change: true}
        ]
        filters: {exclude: ["size xxl", "size xl", "size l"], min-discount: 58}
      }

      scan {
        monitoring-frequency: 15m
        monitoring-requests: [
          //{search-criteria: {category: "gpu-nvidia-gaming", query: "all"}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }
    
      ebay {
        monitoring-frequency: 10m
        monitoring-requests: [
          //{search-criteria: {item-kind: "generic", query: "nanoleaf shapes", category: "smart-lighting"}, monitor-stock-change: false, monitor-price-change: true}
        ]
      }
    }

    deals-finder {
      ebay {
        search-frequency: 60s
        search-requests: [
          {search-criteria: {query: "PS4", item-kind: "video-game", category: "games-console"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "XBOX ONE", item-kind: "video-game", category: "games-console"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "PS5", item-kind: "video-game", category: "games-console"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "XBOX SERIES", item-kind: "video-game", category: "games-console"}, min-margin: 45, max-quantity: 10}
          {search-criteria: {query: "SWITCH", item-kind: "video-game", category: "games-console"}, min-margin: 45, max-quantity: 10}
        ]
        delay-between-requests: 5s
      }
    }
kind: ConfigMap
metadata:
  name: fs2-app-core-config
