apiVersion: v1
kind: Service
metadata:
  name: "fs2-ebay-app-frontend-extlb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "fs2-ebay-app-frontend"
---
apiVersion: v1
kind: Service
metadata:
  name: "fs2-ebay-app-frontend"
spec:
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: "fs2-ebay-app-frontend"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fs2-ebay-app-frontend"
  labels:
    app: "fs2-ebay-app-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "fs2-ebay-app-frontend"
  template:
    metadata:
      labels:
        app: "fs2-ebay-app-frontend"
    spec:
      containers:
        - name: "frontend"
          image: "kirill1/fs2-ebay-app-frontend:latest"
          env:
            - name: FS2_EBAY_APP_CORE_URL
              value: "http://fs2-app-core:8080"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5