addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.11.7")
addSbtPlugin("com.github.sbt"   % "sbt-javaagent"       % "0.2.0")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"        % "0.5.6")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.5.6")
addSbtPlugin("com.github.sbt"   % "sbt-github-actions"  % "0.30.0")
