name: Deploy to Heroku
on: [workflow_dispatch]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Stage docker image
        run: sbt docker:stage
      - name: Push to heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fs2-ebay"
          heroku_email: "immotional@aol.com"
          usedocker: true
          appdir: ./core/target/docker/stage
