name: Deploy to Heroku
on: [workflow_dispatch]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fs2-ebay-proxy"
          heroku_email: "immotional@aol.com"
          usedocker: true
          appdir: ./proxy
