name: Deploy Proxy to Heroku
on: [workflow_dispatch]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: amazon-corretto@1.17
      - name: Stage docker image
        run: sbt docker:stage
      - name: Push to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fs2-proxy"
          heroku_email: "immotional@aol.com"
          usedocker: true
          appdir: ./proxy/target/docker/stage
