name: Publish to Docker Hub registry
on:
  workflow_dispatch:

jobs:

  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_URI: "registry.hub.docker.com"
      DOCKER_USERNAME: "kirill1"
      APP_NAME: "fs2-app"
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: "registry.hub.docker.com"
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API_KEY }}
      - name: Setup Java (temurin@21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Build and push Docker images
        run: sbt docker:publish
      - name: Build and push Frontend Docker image
        run: |-
          FRONTEND_IMAGE="${DOCKER_REPO_URI}/${DOCKER_USERNAME}/${APP_NAME}-frontend"
          docker build -t ${FRONTEND_IMAGE}:latest -t ${FRONTEND_IMAGE}:${GITHUB_SHA::8} modules/frontend/
          docker push -a ${FRONTEND_IMAGE}
