name: Publish to GCR
on: [workflow_dispatch]

jobs:

  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_URI: "us.gcr.io"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: fs2-app
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - uses: olafurpg/setup-scala@v11
        with:
          java-version: amazon-corretto@1.19
      - name: Build and push Docker images
        run: sbt docker:publish