name: Publish to OKTETO container registry
on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["CI"]
#    types:
#      - completed

jobs:

  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_URI: "registry.cloud.okteto.net"
      DOCKER_USERNAME: "kirill5k"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: "registry.cloud.okteto.net"
          username: "kirill5k"
          password: ${{ secrets.OKTETO_API_KEY }}

      - uses: olafurpg/setup-scala@v11
        with:
          java-version: amazon-corretto@1.17
      - name: Build and push Docker images
        run: sbt docker:publish

      - name: Build and push Frontend Docker image
        env:
          DOCKER_REPO_URL: ${DOCKER_REPO_URI}/${DOCKER_USERNAME}/fs2-ebay-app-frontend
        run: |-
          echo $DOCKER_REPO_URL
          docker build -t ${DOCKER_REPO_URI}/${DOCKER_USERNAME}/fs2-ebay-app-frontend:latest -t ${DOCKER_REPO_URI}/${DOCKER_USERNAME}/fs2-ebay-app-frontend:${GITHUB_SHA::8} frontend/
          docker push -a ${DOCKER_REPO_URI}/${DOCKER_USERNAME}/fs2-ebay-app-frontend
