name: Publish to OKTETO container registry
on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["CI"]
#    types:
#      - completed

jobs:

  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_URI: "registry.hub.docker.com"
      DOCKER_USERNAME: "kirill1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: "registry.hub.docker.com"
          username: "kirill1"
          password: ${{ secrets.DOCKER_HUB_API_KEY }}

      - uses: olafurpg/setup-scala@v11
        with:
          java-version: amazon-corretto@1.19
      - name: Build and push Docker images
        run: sbt docker:publish
